name             'docker_configuration'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures docker_configuration'
long_description 'Installs/Configures docker_configuration'
version          '0.1.0'
depends 'docker', '~>1.0.14'
