name             'jenkins'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures jenkins'
long_description 'Installs/Configures jenkins'
version          '0.1.0'
