name             'google-chrome'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures google-chrome'
long_description 'Installs/Configures google-chrome'
version          '0.1.0'
