name             'custom_resource'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures custom_resource'
long_description 'Installs/Configures custom_resource'
version          '0.1.0'
