name             'make_folders'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures make_folders'
long_description 'Installs/Configures make_folders'
version          '0.1.0'
